"""Report Compiler Agent — synthesizes all research outputs into a beautiful HTML report."""

from langchain_core.prompts import ChatPromptTemplate


REPORT_TEMPLATE = """You are a professional financial report writer. Your task is to compile all research reports, debates, and risk analysis into a single clean, well-structured HTML report suitable for conversion to PDF.

IMPORTANT RULES:
- Use ONLY inline CSS styles (NO external stylesheets, NO classes, NO Tailwind)
- Use ONLY hex color codes (#ffffff, #1f2937, #2563eb, etc.) — NEVER use oklch(), ok lab(), lch(), or lab()
- The HTML must be self-contained and work standalone
- Use Arial/Helvetica font-family
- Tables should have visible borders
- Use a clean professional layout with good spacing

COLOR PALETTE (use these exact hex values):
- Primary blue: #2563eb
- Dark text: #1f2937, #111827
- Medium gray text: #4b5563, #6b7280
- Light gray backgrounds: #f3f4f6, #f9fafb
- Green (buy/bull): #16a34a, #f0fdf4
- Red (sell/bear): #dc2626, #fef2f2
- Amber (hold/warning): #f59e0b, #fffbeb
- Purple: #7c3aed, #f5f3ff
- Emerald: #059669, #ecfdf5
- White: #ffffff
- Light blue: #eff6ff, #dbeafe

REPORT STRUCTURE:
1. **Top accent bar**: Full-width gradient bar (blue-purple-green)
2. **Header**: "Trading Analysis Report" label, ticker name, date, duration
3. **Signal badge**: Color-coded badge (green=buy, red=sell, amber=hold)
4. **Stats bar**: LLM calls, tool calls, tokens, cost in pills
5. **Executive Summary**: 2-3 paragraph synthesis of all findings
6. **Final Trade Decision**: Prominent callout box with entry, stop-loss, targets
7. **Analyst Reports Section**: Each report as a card with numbered header
   - Market & Technical Report
   - Sentiment & Social Media Report  
   - News Report
   - Fundamentals Report
   - Research Manager - Investment Plan
   - Trader - Execution Plan
8. **Bull vs Bear Debate**: Side-by-side columns (green left, red right)
9. **Risk Analysis Debate**: Three rows (aggressive, neutral, conservative)
10. **Footer**: "Generated by Indian Trading Agent", timestamp

LAYOUT SPECS:
- Total width: ~780px (A4 compatible)
- Font sizes: heading 28px ticker, 14px section titles, 12px body text
- Use <table> for structured data
- Use <strong> for emphasis (render as bold)
- Use <em> for secondary emphasis
- Code/technical terms in <code> tags
- Section cards: white background, subtle gray border, rounded corners

Here is the analysis data to compile:

TICKER: {ticker}
TRADE DATE: {trade_date}
SIGNAL: {signal}
DURATION: {duration}

STATS:
- LLM Calls: {llm_calls}
- Tool Calls: {tool_calls}  
- Total Tokens: {total_tokens}
- Cost: ${cost_usd} USD / ₹{cost_inr} INR

MARKET & TECHNICAL REPORT:
{market_report}

SENTIMENT & SOCIAL MEDIA REPORT:
{sentiment_report}

NEWS REPORT:
{news_report}

FUNDAMENTALS REPORT:
{fundamentals_report}

INVESTMENT PLAN (Research Manager):
{investment_plan}

TRADER EXECUTION PLAN:
{trader_plan}

FINAL TRADE DECISION:
{final_decision}

BULL DEBATE:
{bull_debate}

BEAR DEBATE:
{bear_debate}

RISK DEBATE - AGGRESSIVE:
{aggressive_debate}

RISK DEBATE - CONSERVATIVE:
{conservative_debate}

RISK DEBATE - NEUTRAL:
{neutral_debate}

Generate ONLY the HTML output. Do NOT wrap it in ```html markers. Do NOT add any explanation before or after. Start directly with <!DOCTYPE html>."""


def compile_report(llm, ticker: str, trade_date: str, signal: str, duration_str: str,
                   stats: dict, reports: dict, debates: dict, risk_debates: dict) -> str:
    """Use the LLM to compile all research into a single beautiful HTML report.
    
    Returns the HTML string.
    """
    prompt = ChatPromptTemplate.from_messages([
        ("system", REPORT_TEMPLATE),
    ])
    
    chain = prompt | llm
    
    # Safely convert stats values that might already be strings
    cost_usd_raw = stats.get("cost_usd", 0)
    cost_inr_raw = stats.get("cost_inr", 0)
    try:
        cost_usd_val = round(float(cost_usd_raw), 4)
    except (ValueError, TypeError):
        cost_usd_val = 0
    try:
        cost_inr_val = round(float(cost_inr_raw), 2)
    except (ValueError, TypeError):
        cost_inr_val = 0

    result = chain.invoke({
        "ticker": ticker,
        "trade_date": trade_date,
        "signal": signal or "N/A",
        "duration": duration_str,
        "llm_calls": stats.get("llm_calls", 0),
        "tool_calls": stats.get("tool_calls", 0),
        "total_tokens": str(stats.get("total_tokens", 0)),
        "cost_usd": str(cost_usd_val),
        "cost_inr": str(cost_inr_val),
        "market_report": reports.get("market_report", "")[:8000],
        "sentiment_report": reports.get("sentiment_report", "")[:8000],
        "news_report": reports.get("news_report", "")[:8000],
        "fundamentals_report": reports.get("fundamentals_report", "")[:8000],
        "investment_plan": reports.get("investment_plan", "")[:6000],
        "trader_plan": reports.get("trader_investment_plan", "")[:4000],
        "final_decision": reports.get("final_trade_decision", "")[:3000],
        "bull_debate": debates.get("bull", "")[:6000],
        "bear_debate": debates.get("bear", "")[:6000],
        "aggressive_debate": risk_debates.get("aggressive", "")[:5000],
        "conservative_debate": risk_debates.get("conservative", "")[:5000],
        "neutral_debate": risk_debates.get("neutral", "")[:5000],
    })
    
    content = result.content if hasattr(result, 'content') else str(result)
    return content